name: CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ master, Develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
            cd shichi 
            npm install --force
        
      - name: Run tests
        run: npm test